sceNpSignaling library stub and log fix
SysRay/psOff_public pull request #150
Opened 2024-05-03 20:42 UTC by kr1spy2115

2024-05-03 20:58 UTC, SysRay requested changes

2024-05-03 20:58 UTC, SysRay commented on modules/libSceNpSignaling/types.h
> +typedef void (*SceNpSignalingHandler)(uint32_t ctxId, uint32_t subjectId, int event, int errorCode, void* arg);
SYSV_ABI

2024-05-04 05:19 UTC, kr1spy2115 commented on modules/libSceNpSignaling/types.h
> +typedef void (*SceNpSignalingHandler)(uint32_t ctxId, uint32_t subjectId, int event, int errorCode, void* arg);
resolved

2024-05-04 08:04 UTC, SysRay approved these changes

2024-05-04 08:04 UTC, merged